### ISSUE TITLE
Investigate using GitHub Actions for CI tests

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3708]
We really should look into using [GitHub Actions (click here for infos)](https://help.github.com/en/articles/about-github-actions) for CI testing. It seems they allow up to 20 (!) concurrent builds; which is 4 times as much as what Travis allows us; and in addition, this limit seems to be *per repository* not per organization (!). I don't know how fast the VMs they give you are, but this could mean a substantial speedup of our CI turn around times on busy days.

In addition, they seem to support Docker in a very nice fashion, which makes this quite interesting for GAP packages, which could potentially use our premade Docker containers for testing, thus potentially reducing their CI turn around times, too (but this is just hypothetical, as downloading those docker images also takes up resources, so I have no idea what will be fastest in the end).

GitHub Actions also support Windows and macOS, and I'd be in particular interested in migrating our CI tests away from AppVeyor to that.

**Comment by fingolfin** [comment]
I think the way this is done for Julia package is instructive. See e.g. here: https://raw.githubusercontent.com/oscar-system/Polymake.jl/master/.github/workflows/runtests.yml

The build steps in there look like this (I removed some less important bits):
```yaml
    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
```
Each `uses: julia-actions/...` line triggers the code in one of the repos under https://github.com/julia-actions -- so this roughly corresponds to what we've been doing by cloning the https://github.com/gap-system/pkg-ci-scripts.git repository.



However, we do not *need* to do it this way, we merely *can*. We can also just use a mostly raw translation of what we do in our `.travis.yml` files. It's just that by encapsulating these things into "GitHub Actions" as done for Julia stuff above is the more idiomatic way and may simplify things a bit on the long run. But many variations are possible. E.g. we could also use Docker images with GAP preinstalled
