### ISSUE TITLE
GH Actions: upload generated manuals (PDF and/or HTML) as artifacts

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4181]
@ssiccha did that for GAP packages, it would be good to have this here as well, so that one can easily review documentation changes.

**Comment by fingolfin** [comment]
I am talking about https://github.com/gap-packages/recog/blob/ca5433ad8cd748b93e0044fab4f6c97e595ac69f/.github/workflows/CI.yml#L42-L46 
```
      - name: "Upload documentation"
        uses: actions/upload-artifact@v1
        with:
          name: manual
          path: ./doc/manual.pdf
```
