### ISSUE TITLE
CI: re-enable .gap-package-cache under GitHub Actions

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4268]
Some time ago, @ChrisJefferson added `etc/ci-download.sh` which look for a `.gap-package-cache` directory when run in the CI, to get cached files from there. This was only used in Travis, and we are not using Travis anymore.

But GitHub actions also has a caching feature, namely the [`actions/cache` action](https://github.com/actions/cache), which we could look into using. We use it for various OSCAR packages, see e.g. https://github.com/oscar-system/Oscar.jl/blob/b032736116a9ce5701577134a0cbe60630986131/.github/workflows/CI.yml#L43-L53
```
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
```
