### ISSUE TITLE
add big-endian support to GH Actions

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#5068]
This is requested in 
https://github.com/gap-system/gap/blob/a2d1f49f54479a3896d4674d2ede6ad88abbb31d/.github/workflows/CI.yml#L151

A quick way may be found in https://github.com/wasm3/wasm3/blob/fa18e9ece4dd45371deac69ded32838470a55c1b/.github/workflows/tests.yml#L79

```
big-endian-i32-constant:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the qemu container
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Run tests
      run: docker run --rm --interactive --mount type=bind,source=$(pwd),target=/host s390x/alpine sh -c "apk add build-base cmake git --update-cache && cd /host && mkdir build && cd build && cmake .. && cd .. && cmake --build build && echo wasm3 built && echo AGFzbQEAAAAGBgF/AEElCwcLAQdteWNvbnN0AwAACARuYW1lAgEA | base64 -d > myconst.wasm && echo ':get-global myconst' | ./build/wasm3 --repl myconst.wasm && echo ':get-global myconst' | ./build/wasm3 --repl myconst.wasm 2>&1 | grep 37"
```
(obviously the 1-line script in the last line will need adjustments, such as switching from `apline` to something less insane, and of course what's done there (i.e. building/testing, too.)
