### ISSUE TITLE
Migrate ChrisJefferson/sage-windows to gap-system ? And/or merge it back into `sagemath/sage-windows`?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5288]
To quote `.github/workflows/release.yml`:
```
      # The following repository should eventually be owned by a GAP-related
      # organisation, and perhaps ultimately it could/should be re-integrated
      # with the original sagemath/sage-windows repository.
      - name: "Clone the Windows installer maker scripts"
        uses: actions/checkout@v3
        with:
          repository: ChrisJefferson/sage-windows
          ref: master
          path: sage-windows
```
So we are using https://github.com/ChrisJefferson/sage-windows -- perhaps it could be moved under `gap-system` (and perhaps be renamed, say to `gap-cygwin`?)
